#!/usr/bin/env bash
# Deploy the teslcam server backend to a VPS.
#
#   scripts/deploy-server.sh setup <listen-addr>   one-time server setup
#   scripts/deploy-server.sh deploy                build + ship + restart
#   scripts/deploy-server.sh caddy <hostname>      add a TLS reverse-proxy vhost
#   scripts/deploy-server.sh status                service status
#   scripts/deploy-server.sh logs [n]              last n log lines (default 100)
#
# Target host is adri@vps; override with TESLCAM_VPS=user@host.
#
# The API requires a bearer token (generated by setup); /healthz is open.
# The server listens on 127.0.0.1 and is fronted by a TLS reverse proxy
# (Caddy — see the `caddy` subcommand) on a public subdomain like
# api.example.com — TLS protects the token in transit; the token
# authenticates the agent.
#
# Analysis + alerts are native (in-process): the server takes -gemini-model /
# -gemini-media-resolution (reading GEMINI_API_KEY from the env) and optional
# -telegram-* flags. There is no external analyzer to ship; the launcher
# script assembles those flags from server.env at start time (empty vars =
# feature off), since the server rejects empty required config by design.
#
# Server layout (created by setup):
#   /usr/local/bin/teslcam-server        binary (replaced by deploy)
#   /usr/local/bin/teslcam-server-start  launcher: builds flags from server.env
#   /var/lib/teslcam                     data: SQLite DB + received clips
#   /etc/teslcam/server.env              config: listen addr, Gemini, Telegram
#   /etc/teslcam/ingest.token            API bearer token (give it to the agent)
#   /etc/teslcam/telegram.token          Telegram bot token (optional)
#   /etc/systemd/system/teslcam-server.service
set -euo pipefail

HOST="${TESLCAM_VPS:-adri@vps}"
SSH=(ssh -o ConnectTimeout=10 "$HOST")
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

usage() {
  cat <<EOF
usage: $0 <command>

  setup <listen-addr>   one-time server setup (user, dirs, config, token,
                        launcher, systemd unit); listen-addr should be local,
                        e.g. 127.0.0.1:8090, behind a TLS reverse proxy
  deploy                cross-compile, upload binary, restart, health-check
  caddy <hostname>      idempotently add a Caddy vhost that TLS-terminates
                        <hostname> and reverse-proxies to the server
  status                systemctl status of the service
  logs [n]              last n journal lines (default 100)

target host: $HOST (override with TESLCAM_VPS=user@host)
EOF
  exit 1
}
say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# run_sudo NAME=value... <<'EOF' ... — runs a script as root on the VPS.
# The script travels base64-encoded so quoting is a non-issue and stdin
# stays free for sudo's password prompt (hence ssh -t).
run_sudo() {
  local b64
  b64="$(base64 <"/dev/stdin" | tr -d '\n')"
  ssh -t -o ConnectTimeout=10 "$HOST" \
    "echo $b64 | base64 -d | sudo env ${*:-_=_} bash -s"
}

remote_arch() {
  local m
  m="$("${SSH[@]}" uname -m)"
  case "$m" in
    x86_64) echo amd64 ;;
    aarch64 | arm64) echo arm64 ;;
    *) die "unsupported VPS architecture: $m" ;;
  esac
}

cmd_setup() {
  local listen="${1:-}"
  [[ -n "$listen" ]] || die "usage: $0 setup <listen-addr>   (e.g. 127.0.0.1:8090, behind a TLS reverse proxy)"

  say "setting up $HOST (listen: $listen)"
  run_sudo "LISTEN=$listen" <<'EOF'
set -euo pipefail

# Service user + directories.
id -u teslcam >/dev/null 2>&1 || useradd --system --home /var/lib/teslcam --shell /usr/sbin/nologin teslcam
mkdir -p /var/lib/teslcam /etc/teslcam
chown teslcam:teslcam /var/lib/teslcam

# Config: created once, never overwritten (it holds the API key).
if [[ ! -f /etc/teslcam/server.env ]]; then
  cat > /etc/teslcam/server.env <<ENV
# teslcam server config (systemd EnvironmentFile)
LISTEN_ADDR=$LISTEN
# Gemini analysis is off until BOTH GEMINI_MODEL and GEMINI_API_KEY are set;
# then: systemctl restart teslcam-server. GEMINI_MEDIA_RESOLUTION is optional
# (low|medium|high; empty = API default; low is ~4x cheaper).
GEMINI_API_KEY=
GEMINI_MODEL=
GEMINI_MEDIA_RESOLUTION=
# Telegram alerts are off unless TELEGRAM_CHAT_ID is set AND the bot token is
# written to /etc/teslcam/telegram.token; then: systemctl restart teslcam-server.
TELEGRAM_CHAT_ID=
ENV
  chmod 640 /etc/teslcam/server.env
  chown root:teslcam /etc/teslcam/server.env
  echo "wrote /etc/teslcam/server.env"
else
  echo "/etc/teslcam/server.env already exists — left untouched"
fi

# API bearer token: created once, never overwritten.
if [[ ! -f /etc/teslcam/ingest.token ]]; then
  head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > /etc/teslcam/ingest.token
  chmod 640 /etc/teslcam/ingest.token
  chown root:teslcam /etc/teslcam/ingest.token
  echo "wrote /etc/teslcam/ingest.token"
else
  echo "/etc/teslcam/ingest.token already exists — left untouched"
fi

# Telegram bot token placeholder: created once (empty), never overwritten.
# Paste the bot token here and set TELEGRAM_CHAT_ID in server.env to enable.
if [[ ! -f /etc/teslcam/telegram.token ]]; then
  install -m 640 -o root -g teslcam /dev/null /etc/teslcam/telegram.token
  echo "wrote empty /etc/teslcam/telegram.token"
else
  echo "/etc/teslcam/telegram.token already exists — left untouched"
fi

# Launcher: assembles the server flags from server.env, passing optional flags
# only when their env var is non-empty (the server rejects empty required
# config, so never hand it an empty flag value). Overwritten on every setup.
cat > /usr/local/bin/teslcam-server-start <<'WRAP'
#!/usr/bin/env bash
# Launched by systemd with server.env already loaded into the environment.
# Fails fast (before exec'ing the server) on inconsistent config.
set -euo pipefail

# Required config (server.env). Under `set -u` an unset var aborts here.
args=(
  -data /var/lib/teslcam
  -listen "$LISTEN_ADDR"
  -token-file /etc/teslcam/ingest.token
)

# Gemini analysis: opt-in. Model implies a key.
if [[ -n "${GEMINI_MODEL:-}" ]]; then
  if [[ -z "${GEMINI_API_KEY:-}" ]]; then
    echo "teslcam-server-start: GEMINI_MODEL set but GEMINI_API_KEY is empty in /etc/teslcam/server.env" >&2
    exit 1
  fi
  args+=(-gemini-model "$GEMINI_MODEL")
  if [[ -n "${GEMINI_MEDIA_RESOLUTION:-}" ]]; then
    args+=(-gemini-media-resolution "$GEMINI_MEDIA_RESOLUTION")
  fi
fi

# Telegram alerts: opt-in. Chat ID implies a non-empty token file.
if [[ -n "${TELEGRAM_CHAT_ID:-}" ]]; then
  token_file=/etc/teslcam/telegram.token
  if [[ ! -s "$token_file" ]] || ! grep -q '[^[:space:]]' "$token_file"; then
    echo "teslcam-server-start: TELEGRAM_CHAT_ID is set but $token_file is empty — paste the bot token there" >&2
    exit 1
  fi
  args+=(-telegram-chat-id "$TELEGRAM_CHAT_ID" -telegram-token-file "$token_file")
fi

exec /usr/local/bin/teslcam-server "${args[@]}"
WRAP
chmod 755 /usr/local/bin/teslcam-server-start
echo "wrote /usr/local/bin/teslcam-server-start"

cat > /etc/systemd/system/teslcam-server.service <<'UNIT'
[Unit]
Description=TeslaCam server
After=network-online.target
Wants=network-online.target

[Service]
User=teslcam
EnvironmentFile=/etc/teslcam/server.env
Environment=HOME=/var/lib/teslcam
# The launcher reads server.env and builds the flag set (analysis/alerts are
# opt-in), then execs the server binary.
ExecStart=/usr/local/bin/teslcam-server-start
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
ProtectSystem=full
ReadWritePaths=/var/lib/teslcam

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable teslcam-server
echo "setup done"
EOF

  say "setup complete — next steps:"
  echo "  1. (optional) enable analysis: set GEMINI_API_KEY + GEMINI_MODEL in"
  echo "       /etc/teslcam/server.env on the VPS"
  echo "  2. (optional) enable alerts: paste the bot token into"
  echo "       /etc/teslcam/telegram.token and set TELEGRAM_CHAT_ID in server.env"
  echo "  3. run: $0 deploy"
  echo "  4. expose it: $0 caddy api.example.com"
  echo "  5. copy the API token to the agent's -token-file:"
  echo "       ssh $HOST sudo cat /etc/teslcam/ingest.token"
}

cmd_deploy() {
  local arch tmp
  arch="$(remote_arch)"
  tmp="$(mktemp -d)"
  # Expand now: tmp is local, and an EXIT trap fires after it goes out of scope.
  trap "rm -rf '$tmp'" EXIT

  say "building teslcam-server for linux/$arch"
  (cd "$ROOT" && GOOS=linux GOARCH="$arch" CGO_ENABLED=0 go build -trimpath -o "$tmp/teslcam-server" ./cmd/teslcam-server)

  say "uploading binary"
  scp -q "$tmp/teslcam-server" "$HOST:/tmp/teslcam-server.new"

  say "installing binary, restarting, health-checking"
  run_sudo <<'EOF'
set -euo pipefail
install -m 755 /tmp/teslcam-server.new /usr/local/bin/teslcam-server
rm -f /tmp/teslcam-server.new
systemctl restart teslcam-server

addr="$(grep '^LISTEN_ADDR=' /etc/teslcam/server.env | cut -d= -f2)"
for _ in $(seq 1 10); do
  if curl -fsS --max-time 2 "http://$addr/healthz" >/dev/null 2>&1; then
    echo "healthy: http://$addr"
    exit 0
  fi
  sleep 1
done
echo "server not responding on $addr after 10s" >&2
systemctl status teslcam-server --no-pager -n 20 || true
exit 1
EOF
  say "deployed"
}

cmd_caddy() {
  local hostname="${1:-}"
  [[ -n "$hostname" ]] || die "usage: $0 caddy <hostname>   (e.g. api.example.com)"

  say "configuring Caddy vhost $hostname on $HOST"
  run_sudo "VHOST=$hostname" <<'EOF'
set -euo pipefail
CADDYFILE=/etc/caddy/Caddyfile
[[ -f "$CADDYFILE" ]] || { echo "$CADDYFILE not found — is Caddy installed?" >&2; exit 1; }

addr="$(grep '^LISTEN_ADDR=' /etc/teslcam/server.env | cut -d= -f2)"
[[ -n "$addr" ]] || { echo "LISTEN_ADDR missing from /etc/teslcam/server.env" >&2; exit 1; }

# Idempotent: skip if a block already opens with this hostname.
if grep -qE "(^|[[:space:]])${VHOST}([[:space:]]|\{)" "$CADDYFILE"; then
  echo "$VHOST already present in $CADDYFILE — left untouched"
  exit 0
fi

cat >> "$CADDYFILE" <<BLOCK

$VHOST {
	reverse_proxy $addr {
		health_uri /healthz
	}
}
BLOCK
echo "appended $VHOST -> $addr to $CADDYFILE"

if ! caddy validate --config "$CADDYFILE" --adapter caddyfile >/dev/null 2>&1; then
  echo "WARNING: caddy validate reported problems with $CADDYFILE" >&2
fi
systemctl reload caddy
echo "reloaded caddy"
EOF
  say "caddy vhost ready — https://$hostname (once DNS points here)"
}

cmd_status() { "${SSH[@]}" systemctl status teslcam-server --no-pager; }
cmd_logs() { "${SSH[@]}" journalctl -u teslcam-server --no-pager -n "${1:-100}"; }

case "${1:-}" in
  setup) shift; cmd_setup "$@" ;;
  deploy) cmd_deploy ;;
  caddy) shift; cmd_caddy "$@" ;;
  status) cmd_status ;;
  logs) shift; cmd_logs "$@" ;;
  *) usage ;;
esac
